services:
  nginx:
    hostname: nginx
    build:
      context: requirements/nginx
    container_name: nginx
    env_file:
     - .env
    ports:
     - 8080:443
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
#    volumes:
#      - ./requirements/front:/var/www
    networks:
      - transcendence
    restart: unless-stopped

  fastify:
    hostname: fastify
    build:
      context: requirements/fastify
    container_name: fastify
    env_file:
      - .env
 #   volumes:
 #     - fastify:/app
    networks:
      - transcendence
    restart: unless-stopped

#volumes:
#  nginx:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ../data/nginx
#  fastify:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ../data/fastify
#
networks:
  transcendence:
    name: transcendence
