services:
  nginx:
    hostname: nginx
    build:
      context: ../
      dockerfile: srcs/requirements/nginx/Dockerfile
    container_name: nginx
    env_file:
     - .env
    ports:
     - 1083:443
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
