services:
  nginx:
    hostname: nginx
    build:
      context: requirements/nginx
    container_name: nginx
    env_file:
     - .env
    ports:
     - 8080:443
    volumes:
      - ./requirements/front:/var/www
      - nginx:/modsec_logs
    depends_on:
      - logstash
    networks:
      - transcendence
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000" #gelf doesnt use Docker DNS hence localhost:5000 for logstash--wouldnt work in prod tho lol
        tag: "ngnix-service"

  database:
    hostname: database
    build:
      context: requirements/database
    container_name: database
    env_file:
      - .env
    volumes:
      - database:/data
    depends_on:
      - logstash
    networks:
      - transcendence
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000"
        tag: "database-service"

  pong:
    hostname: pong
    build:
      context: requirements/pong
    container_name: pong
    env_file:
      - .env
    depends_on:
      - database
      - logstash
    networks:
      - transcendence
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000"
        tag: "pong-service"

  authentication:
    hostname: authentication
    build:
      context: requirements/authentication
    container_name: authentication
    env_file:
      - .env
    depends_on:
      - database
      - logstash
    networks:
      - transcendence
    restart: unless-stopped
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:5000"
        tag: "auth-service"

  hashicorp-vault:
    hostname: hashicorp-vault
    build:
      context: requirements/hashicorp-vault
    container_name: hashicorp-vault
    env_file:
      - .env
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./requirements/hashicorp-vault/config:/vault/config
      - ./requirements/hashicorp-vault/certs:/vault/certs:ro
      - ./requirements/hashicorp-vault/data:/vault/data
    networks:
      - transcendence
    restart: unless-stopped
    

volumes:
  nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/modsec_logs
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/database

networks:
  transcendence:
    name: transcendence
