services:
  nginx:
    hostname: nginx
    build:
      context: requirements/nginx
    container_name: nginx
    env_file:
     - .env
    ports:
     - 8080:443
    volumes:
      - ./requirements/front:/var/www
    networks:
      - transcendence
    restart: unless-stopped

  database:
    hostname: database
    build:
      context: requirements/database
    container_name: database
    env_file:
      - .env
    volumes:
      - database:/data
    networks:
      - transcendence
    restart: unless-stopped

  elasticsearch:
    hostname: elasticsearch
    build:
      context: requirements/elk
    platform: linux/amd64
    container_name: elasticsearch
    env_file:
      - .env
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - transcendence
    restart: unless-stopped

  pong:
    hostname: pong
    build:
      context: requirements/pong
    container_name: pong
    env_file:
      - .env
    depends_on:
      - database
      - elasticsearch
    networks:
      - transcendence
    restart: unless-stopped

  authentication:
    hostname: authentication
    build:
      context: requirements/authentication
    container_name: authentication
    env_file:
      - .env
    depends_on:
      - database
      - elasticsearch
    networks:
      - transcendence
    restart: unless-stopped

volumes:
  nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/nginx
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../data/database

networks:
  transcendence:
    name: transcendence
