services:
  nginx:
    hostname: nginx
    build:
      context: ../
      dockerfile: ./srcs/requirements/nginx/Dockerfile
    container_name: nginx
    env_file:
     - .env
    ports:
     - 8080:443
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    networks:
      - transcendence
    restart: unless-stopped

  fastify:
    hostname: fastify
    build:
      context: requirements/fastify
    container_name: fastify
    env_file:
     - .env
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    name: transcendence
